name: ci

on: push

jobs:

  build:
    runs-on: ubuntu-20.04
    container:
      image: ubuntu:20.04

    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2

    - name: build
      run: |
        export DEBIAN_FRONTEND=noninteractive
        apt update
        apt-get install -y build-essential git clang cmake
        apt-get install -y libstdc++-10-dev libssl-dev libxxhash-dev zlib1g-dev pkg-config
        git clone https://github.com/rui314/mold.git
        cd mold 
        git checkout v1.0.3
        make -j$(nproc) CXX=clang++ CC=clang

    - name: create_tar
      run: |
        cd mold
        tar cvzf ../mold.tar.gz mold mold-wrapper.so
        ls -lah *.tar.gz

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        title: "Development Build"
        files: |
          mold.tar.gz


