name: ci

on: push

jobs:

  build:
    runs-on: ubuntu-20.04
    container:
      image: ubuntu:20.04

    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2

    - name: build
      run: |
        export DEBIAN_FRONTEND=noninteractive
        apt update
        apt-get install -y build-essential git clang cmake
        apt-get install -y libstdc++-10-dev libssl-dev libxxhash-dev zlib1g-dev pkg-config
        git clone https://github.com/rui314/mold.git
        cd mold 
        git checkout v1.0.2
        make -j$(nproc) CXX=clang++


    - uses: actions/upload-artifact@v2
      with:
        name: mold_compile_art
        path: |
          mold/mold
          mold/mold-wrapper.so
