name: ci

on: push

env:
  mold_version: "1.4.1"

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: ubuntu:20.04

    steps:
    - uses: actions/checkout@v2

    - name: prepare system
      run: |
        export DEBIAN_FRONTEND=noninteractive
        curl https://raw.githubusercontent.com/rui314/mold/main/install-build-deps.sh | sudo bash

    - name: build mold
      run: |
        git clone https://github.com/rui314/mold.git
        cd mold 
        git checkout v${mold_version}
        make -j$(nproc) CXX=clang++ CC=clang

    - name: create tar
      run: |
        cd mold
        tar cvzf ../mold.tar.gz mold mold-wrapper.so
        cd ..
        ls -lah *.tar.gz

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "Development Build"
        files: |
          mold.tar.gz

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ env.mold_version }}"
        prerelease: false
        title: "${{ env.mold_version }} Build"
        files: |
          mold.tar.gz

  test_deb:
    needs: [build]
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        container_image:
          [
            "ubuntu:20.04",
            "debian:11",
            "debian:testing",
            "debian:unstable",
          ]
    container:
      image: ${{ matrix.container_image }}
    steps:
    - name: Download from github release
      run: |
        export DEBIAN_FRONTEND=noninteractive
        apt-get update && apt-get install -y wget tar curl libssl-dev libssl1.1
        curl -fsSL https://raw.githubusercontent.com/ren15/mold_ci/HEAD/install.sh | bash
        mold --version

  test_rpm:
    needs: [build]
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        container_image:
          [
            "fedora:35",
          ]
    container:
      image: ${{ matrix.container_image }}
    steps:
    - name: Download from github release
      run: |
        yum install -y tar wget openssl-devel curl
        curl -fsSL https://raw.githubusercontent.com/ren15/mold_ci/HEAD/install.sh | bash
        mold --version

  test_archlinux:
    needs: [build]
    runs-on: ubuntu-20.04
    container:
      image: archlinux:latest
    steps:
    - name: Download from github release
      run: |
        pacman -Sy && pacman -S --noconfirm tar wget openssl curl
        curl -fsSL https://raw.githubusercontent.com/ren15/mold_ci/HEAD/install.sh | bash
        mold --version