name: ci

on: push


jobs:

  build:
    runs-on: ubuntu-20.04
    container:
      image: ubuntu:20.04

    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2

    - name: build
      run: |
        python3 build.py
        ls 
        ls mold

    - uses: actions/upload-artifact@v2
      with:
        name: mold_bin
        path: mold/mold
